name: Resize Images

on:
  workflow_dispatch:

jobs:
  resize-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Process images
        run: |
          exceptions_file="$POST_IMAGE_PATH/exceptions.txt"
          touch "$exceptions_file"   # ensure it exists so we can append

          POST_IMAGE_PATH="assets/images"
          
          while IFS= read -r img; do
            if [ -f "$POST_IMAGE_PATH/$img" ]; then
              echo "Processing $img"
              echo "Before resize:"
              identify "$POST_IMAGE_PATH/$img" || echo "⚠️ identify failed on $img before resize"

              # Try resizing
              if convert "$POST_IMAGE_PATH/$img" -resize 800x -quality 90 "$POST_IMAGE_PATH/$img"; then
                echo "After resize:"
                identify "$POST_IMAGE_PATH/$img" || echo "⚠️ identify failed on $img after resize"
              else
                echo "❌ Resize failed for $img"
                echo "$img" >> "$exceptions_file"
              fi
            else
              echo "❌ File not found: $img"
              echo "$img" >> "$exceptions_file"
            fi
          done < $POST_IMAGE_PATH/new_images.txt

          # Delete list file
          rm -f $POST_IMAGE_PATH/new_images.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Resize images and update exceptions.txt" || echo "No changes to commit"
          git push origin staging
