name: Resize Images

on:
  workflow_dispatch:

jobs:
  resize-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Process images
        run: |
        
          POST_IMAGE_PATH="assets/images"
          
          exceptions_file="$POST_IMAGE_PATH/exceptions.txt"
          touch "$exceptions_file"   # ensure it exists so we can append

          while IFS= read -r img; do
            if [ -f "$POST_IMAGE_PATH/$img" ]; then
              echo "Processing $img"

              # Get width from identify
              width=$(identify -format "%w" "$POST_IMAGE_PATH/$img" 2>/dev/null) || {
                echo "⚠️ identify failed on $img"
                continue
              }

              echo "Before resize:"
              identify "$POST_IMAGE_PATH/$img" || echo "⚠️ identify failed on $img before resize"
              
              if [ "$width" -gt 800 ]; then
                echo "Resizing $img ..."
                if convert "$POST_IMAGE_PATH/$img" -resize 800x -quality 90 "$POST_IMAGE_PATH/$img"; then
                echo "After resize:"
                identify "$POST_IMAGE_PATH/$img" || echo "⚠️ identify failed on $img after resize"
                else
                  echo "❌ Resize failed for $img"
                  echo "$img" >> "$exceptions_file"
                fi
              else
                echo "Skipping $img (width ${width}px ≤ 800px)"
              fi
            else
              echo "❌ File not found: $img"
              echo "$img" >> "$exceptions_file"
            fi
          done < $POST_IMAGE_PATH/new_images.txt

          # Delete list file
          rm -f $POST_IMAGE_PATH/new_images.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "action@github.com"
          git add assets/images
          git commit -m "Resize images and update exceptions.txt" || echo "No changes to commit"
          git push origin staging
       

